GET http://localhost:2000/users
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiZW1haWw0MUBnbWFpbC5jb20iLCJpYXQiOjE2ODc0MDcwMDMsImV4cCI6MTY4NzQwNzAzM30.C6kMGw8D5VjQnTpDlo5UyLtZrXIAiyDI9o43YIR4gbc


####
POST http://localhost:2000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "email1@gmail.com",
    "password": "123456"    
}
###
POST http://localhost:2000/login
Content-Type: application/json

{
    "email":"email41@gmail.com",
    "password":"123456"
}

###
GET http://localhost:2000/token

###
DELETE http://localhost:2000/logout