GET http://localhost:2000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjg3NzUwNjYwLCJleHAiOjE2ODc3NTA2OTB9.NWaj_N11E9FfUnT8qRhg9659opvOA_eE7lcOCBYxVy0
####
POST http://localhost:2000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "admin@gmail.com",
    "password": "123456"    
}
###
POST http://localhost:2000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"123456"
}

###
GET http://localhost:2000/token

###
DELETE http://localhost:2000/logout