GET http://localhost:2000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDYxMjQwLCJleHAiOjE2ODgwNjEyNzB9.IxzcWP7MRcQIwe4frB8cRZ4O_Opgy4yxmmxowR0CGvA
####
POST http://localhost:2000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "email1@gmail.com",
    "password": "123456"    
}
###
POST http://localhost:2000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"123456"
}

###
GET http://localhost:2000/token

###
DELETE http://localhost:2000/logout

###
GET http://localhost:2000/menu